name: app_store_connect
description: Dart client for Apple App Store Connect Api. Create signing certificates, provisioning profiles, upload ipa files and metadata to the App Store and more.

version: 1.0.0
homepage: https://github.com/buijs-dev/app-store-client-dart
repository: https://github.com/buijs-dev/app-store-client-dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  crypto_keys:
  x509:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.2.0